-- Create api_user with read/write privileges (but no schema modifications)
CREATE USER api_user WITH PASSWORD '${API_USER_PASSWORD}';
GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO api_user;
GRANT USAGE ON SCHEMA public TO api_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO api_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public 
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO api_user;

-- Create readonly user
CREATE USER readonly WITH PASSWORD '${READONLY_PASSWORD}';
GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO readonly;
GRANT USAGE ON SCHEMA public TO readonly;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA public 
    GRANT SELECT ON TABLES TO readonly; 